### ISSUE TITLE
关于License

### ISSUE THREAD

**Issue by grzhan** [NextMoe/hexo-tag-dplayer#2]
原项目hexo-tag-aplayer是使用MIT License，作为可能是最宽松的开源协议MIT基本上没有什么约束。情理上的话告知一下原开发者（最好经过同意）就好了。

MIT也不具有传染性，也就是说此项目并不强制使用MIT协议，所以可以考虑使用相对限制强的协议来保护自己的劳动成果，甚至商业化也没有问题。

看到README就跑过来说一下（

**Comment by Myer921** [comment]
好的 我知道了 不过这个代码毕竟不是我主要修改
这个我会通知一下他的 
其实另外一个人想用WTFPL（
