### ISSUE TITLE
求帮助

### ISSUE THREAD

**Issue by mxdlsm** [NextMoe/hexo-tag-dplayer#25]
本人小白，不太明吧，我是在一个自定义的ejs文件里怎么用呀，我把定制下面那些代码拷贝进去怎么什么都不显示呀？

**Comment by dixyes** [comment]
不用动ejs，在你的博客目录（hexo s和hexo g的目录）执行`npm install hexo-tag-dplayer --save`来安装

在md里面使用{% dplayer key=value ... %}来嵌入dplayer，用法见https://github.com/MoePlayer/hexo-tag-dplayer#usage

**Comment by mxdlsm** [comment]
只能用md么？不想嵌入到文章里，我想要实现这种效果，直接在html上显示。不用写ejs?
<img width="924" alt="_20181107194849" src="https://user-images.githubusercontent.com/22886455/48130097-6fafe300-e2c6-11e8-8bac-7ebaf335452c.png">

**Comment by dixyes** [comment]
直接使用video元素或者dplayer

hexo插件只提供dplayer tag的渲染

**Comment by mxdlsm** [comment]
嗷嗷，那下面的定制是什么意思？
