### ISSUE TITLE
利用hexo-blog-encrypt加密，解密之后无法加载该插件

### ISSUE THREAD

**Issue by liujw1007** [NextMoe/hexo-tag-dplayer#26]
#正常情况，没有进行加密
![image](https://user-images.githubusercontent.com/38415583/59481932-1251c500-8e99-11e9-9c6e-ee8a39b2cbe2.png)

#进行了加密之后再解密进入页面
![image](https://user-images.githubusercontent.com/38415583/59481976-5218ac80-8e99-11e9-8055-9175a13712b0.png)

**在`hexo-blog-encrypt`主题上查了一下，说是加密插件覆盖了`windows.onload`函数，可以通过回调函数解决，目前还没找到解决方案**

**Comment by dixyes** [comment]
seems not supported yet due to hacky tag render method, you can use raw tag {%raw%} before support implemented.
可能是现在这个插入标签的脏方法并不兼容hexo-blog-encrypt， 建议先用raw tag来插入html代码（如果rawtag也不行估计就没法了）。

**Comment by dixyes** [comment]
emmm 如果是覆盖了window.onload导致的, 可能不只是hexo-tag-dplayer的问题了，可能需要hexo-blog-encrypt做相关的兼容

**Comment by liujw1007** [comment]
> emmm 如果是覆盖了window.onload导致的, 可能不只是hexo-tag-dplayer的问题了，可能需要hexo-blog-encrypt做相关的兼容

恩恩，谢啦！
